//! World seed and re-exports from generated balance data.

pub use crate::balance_generated::{
    ABANDON_AFTER_DEFICIT_TICKS, BUILDING_ROAD_ACCESS_DISTANCE, LODGE_FIREWOOD_PER_CYCLE,
    LODGE_TIMBER_PER_CYCLE, POPULATION_PER_RESIDENCE, REFORESTER_REGROW_PER_SEC,
    RESIDENCE_FIREWOOD_CAPACITY, RESIDENCE_FIREWOOD_PER_PERSON_PER_SEC, STONE_PER_HARVEST, TICK_DT,
    TICK_MICROS, STARTING_POPULATION,
};

pub const DEFAULT_WORLD_SEED: u64 = 0x71a2e0d;
